"""add_teacher_address

Revision ID: 06de3576811c
Revises: '4abd35d26424'
Create Date: 2026-08-28 18:15:12.368929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06de3576811c'
down_revision: Union[str, None] = '4abd35d26424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('address', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'address')
    # ### end Alembic commands ###
