"""chunk2_academic_people

Revision ID: 4abd35d26424
Revises: '2725544e621a'
Create Date: 2026-08-28 18:11:38.439740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4abd35d26424'
down_revision: Union[str, None] = '2725544e621a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_years_id'), 'academic_years', ['id'], unique=False)
    op.create_index(op.f('ix_academic_years_name'), 'academic_years', ['name'], unique=True)
    op.create_table('school_classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('numeric_grade', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_classes_id'), 'school_classes', ['id'], unique=False)
    op.create_index(op.f('ix_school_classes_name'), 'school_classes', ['name'], unique=True)
    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('class_teacher_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['class_teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_id'), 'sections', ['id'], unique=False)
    op.create_table('subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weekly_periods', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['school_classes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjects_code'), 'subjects', ['code'], unique=True)
    op.create_index(op.f('ix_subjects_id'), 'subjects', ['id'], unique=False)
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=False)
    op.add_column('students', sa.Column('admission_date', sa.Date(), nullable=True))
    op.add_column('students', sa.Column('photo_url', sa.String(length=255), nullable=True))
    op.add_column('students', sa.Column('status', sa.String(length=20), server_default='Active', nullable=False))
    op.add_column('students', sa.Column('class_id', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('section_id', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('academic_year_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'sections', ['section_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'students', 'academic_years', ['academic_year_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'students', 'school_classes', ['class_id'], ['id'], ondelete='SET NULL')
    op.add_column('teachers', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('teachers', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('teachers', sa.Column('salary', sa.Float(), nullable=True))
    op.add_column('teachers', sa.Column('status', sa.String(length=20), server_default='Active', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'status')
    op.drop_column('teachers', 'salary')
    op.drop_column('teachers', 'date_of_birth')
    op.drop_column('teachers', 'gender')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'academic_year_id')
    op.drop_column('students', 'section_id')
    op.drop_column('students', 'class_id')
    op.drop_column('students', 'status')
    op.drop_column('students', 'photo_url')
    op.drop_column('students', 'admission_date')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_code'), table_name='subjects')
    op.drop_table('subjects')
    op.drop_index(op.f('ix_sections_id'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_school_classes_name'), table_name='school_classes')
    op.drop_index(op.f('ix_school_classes_id'), table_name='school_classes')
    op.drop_table('school_classes')
    op.drop_index(op.f('ix_academic_years_name'), table_name='academic_years')
    op.drop_index(op.f('ix_academic_years_id'), table_name='academic_years')
    op.drop_table('academic_years')
    # ### end Alembic commands ###
